### ISSUE TITLE
cgMLST.py can only be run by root

### ISSUE THREAD

**Issue by PyroEndy** [APHA-AMR-VIR/NewVMBasicProgInstall#2]
Need to chmod cgMLST.py to allow it to be run by the user, otherwise get permission denied.

**Comment by jb2cool** [comment]
This is easy to sort, I’ll try and include this when I get a minute or it can wait till I’m back in the UK

**Comment by jb2cool** [comment]
I have created a pull request to address this (from the back seat of a taxi in Bali no less)
